### ISSUE TITLE
500 internal server error 

### ISSUE THREAD

**Issue by javarminator** [ceph/calamari#248]
Dear all 

I followed the installation tutorial and I get this message on the httpd_access.log 

[Thu Jan 22 04:26:33.702685 2015] [:error] [pid 8127] [remote ::1:38160] mod_wsgi (pid=8127): Exception occurred processing WSGI script '/opt/calamari/conf/calamari.wsgi'.
[Thu Jan 22 04:26:33.702756 2015] [:error] [pid 8127] [remote ::1:38160] Traceback (most recent call last):
[Thu Jan 22 04:26:33.702777 2015] [:error] [pid 8127] [remote ::1:38160]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Thu Jan 22 04:26:33.702888 2015] [:error] [pid 8127] [remote ::1:38160]     self.load_middleware()
[Thu Jan 22 04:26:33.702902 2015] [:error] [pid 8127] [remote ::1:38160]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Thu Jan 22 04:26:33.703010 2015] [:error] [pid 8127] [remote ::1:38160]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Thu Jan 22 04:26:33.703023 2015] [:error] [pid 8127] [remote ::1:38160]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Thu Jan 22 04:26:33.703109 2015] [:error] [pid 8127] [remote ::1:38160]     self._setup(name)
[Thu Jan 22 04:26:33.703121 2015] [:error] [pid 8127] [remote ::1:38160]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
[Thu Jan 22 04:26:33.703138 2015] [:error] [pid 8127] [remote ::1:38160]     self._configure_logging()
[Thu Jan 22 04:26:33.703146 2015] [:error] [pid 8127] [remote ::1:38160]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 84, in _configure_logging
[Thu Jan 22 04:26:33.703158 2015] [:error] [pid 8127] [remote ::1:38160]     logging_config_func(self.LOGGING)
[Thu Jan 22 04:26:33.703165 2015] [:error] [pid 8127] [remote ::1:38160]   File "/usr/lib64/python2.7/logging/config.py", line 803, in dictConfig
[Thu Jan 22 04:26:33.704969 2015] [:error] [pid 8127] [remote ::1:38160]     dictConfigClass(config).configure()
[Thu Jan 22 04:26:33.704986 2015] [:error] [pid 8127] [remote ::1:38160]   File "/usr/lib64/python2.7/logging/config.py", line 585, in configure
[Thu Jan 22 04:26:33.705003 2015] [:error] [pid 8127] [remote ::1:38160]     '%r: %s' % (name, e))
[Thu Jan 22 04:26:33.705019 2015] [:error] [pid 8127] [remote ::1:38160] ValueError: Unable to configure handler 'log_file': [Errno 13] Permission denied: '/var/log/calamari/calamari.log'

any answer would be welcome 
Regards 
F

**Comment by dmick** [comment]
Sure looks like a permission error to me.

**Comment by javarminator** [comment]
Thank you for your immediate answer, 
Do you think I should change the permissions of the folder /opt/calamari ?

Regards 
F

**Comment by dmick** [comment]
The permissions error message specifically mentions /var/log/calamari, so
the very first thing I would do is look at the permissions of that path and
the credentials of the process that is failing.

**Comment by GregMeno** [comment]
Haven't heard anything in a while.
If this issue persists feel free to re-open an issue

**Comment by moiseevigor** [comment]
Sorry, got 500 error after the OS upgrade (Ubuntu 14.04) the calamari does not work anymore, I've tried to update calamari and clients with the latest version, but sill the same situation. The error description looks different to the original one but results in the same 550 error. Please help, thanks!

```
==> /var/log/calamari/info.log <==
Wed May 13 10:21:55 2015 :: [IndexSearcher] performing initial index load
Wed May 13 10:21:55 2015 :: [IndexSearcher] reading index data from /var/lib/graphite/index
Wed May 13 10:21:55 2015 :: [IndexSearcher] index reload took 0.000155 seconds (29 entries)

==> /var/log/calamari/calamari.log <==
2015-05-13 10:22:11,042 - ERROR - django.request Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/opt/calamari/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/calamari/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/calamari/venv/lib/python2.7/site-packages/calamari_web-0.1-py2.7.egg/calamari_web/views.py", line 38, in dashboard
    clusters = client.list_clusters()
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/core.py", line 260, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/core.py", line 245, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/core.py", line 217, in _process_response
    reply_event = bufchan.recv(timeout)
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/channel.py", line 267, in recv
    event = self._input_queue.get(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/gevent/queue.py", line 200, in get
    result = waiter.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 568, in get
    return self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
LostRemote: Lost remote after 10s heartbeat

==> /var/log/calamari/httpd_access.log <==
172.16.20.247 - - [13/May/2015:17:21:55 +0200] "GET /dashboard/?target=graph HTTP/1.1" 500 245
```

**Comment by flaviosrcg** [comment]
I am also on the same situation as moiseevigor, after updating ubuntu (14.04).

running supervisorctl status

```
# supervisorctl status
carbon-cache                     RUNNING    pid 14069, uptime 0:35:56
cthulhu                          FATAL      Exited too quickly (process log may have details)
```

and running cthulhu manualy:

```
# /opt/calamari/venv/bin/cthulhu-manager
Traceback (most recent call last):
  File "/opt/calamari/venv/bin/cthulhu-manager", line 9, in <module>
    load_entry_point('calamari-cthulhu==0.1', 'console_scripts', 'cthulhu-manager')()
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/manager/manager.py", line 403, in main
    m = Manager()
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/manager/manager.py", line 165, in __init__
    self._rpc_thread = RpcThread(self)
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/manager/rpc.py", line 450, in __init__
    self._server = zerorpc.Server(RpcInterface(manager))
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/zerorpc/core.py", line 272, in __init__
    methods = ServerBase._filter_methods(Server, self, methods)
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/zerorpc/core.py", line 76, in _filter_methods
    for k in dir(methods)
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/zerorpc/core.py", line 77, in <genexpr>
    if callable(getattr(methods, k))
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/manager/rpc.py", line 26, in __getattribute__
    return object.__getattribute__(self, item)
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/manager/rpc.py", line 328, in _salt_key
    return Key(master_config(config.get('cthulhu', 'salt_config_path')))
TypeError: 'NoneType' object is not callable
```

**Comment by moiseevigor** [comment]
got the same output here on @flaviosrcg's commands

**Comment by Italux** [comment]
I'm facing with the same issue in a new calamari instalation...

**Comment by alexm** [comment]
Followup in #285.

**Comment by chizhang118** [comment]
I am also on the same situation as moiseevigor, after updating ubuntu (14.04).

But running supervisorctl status, it both prints out running. I do not know what is the problem for it.

 
/var/log/calamari/calamari.log <==
2015-05-13 10:22:11,042 - ERROR - django.request Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/opt/calamari/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/calamari/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/calamari/venv/lib/python2.7/site-packages/calamari_web-0.1-py2.7.egg/calamari_web/views.py", line 38, in dashboard
    clusters = client.list_clusters()
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/core.py", line 260, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/core.py", line 245, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/core.py", line 217, in _process_response
    reply_event = bufchan.recv(timeout)
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/channel.py", line 267, in recv
    event = self._input_queue.get(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/gevent/queue.py", line 200, in get
    result = waiter.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 568, in get
    return self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
LostRemote: Lost remote after 10s heartbeat

**Comment by ksingh7** [comment]
@chizhang118   Follow Up in #285

**Comment by ksingh7** [comment]
@chizhang118 @alexm @Italux @moiseevigor @javarminator 

Did you guys managed to fix this ? please share your recipes . Thanks

**Comment by moiseevigor** [comment]
@ksingh7 look `git pull` and recompile resolved my issue, sorry not posted it here beacuse I actually have not tested it in detail. The only I can say the 500 error is gone.

**Comment by ksingh7** [comment]
@moiseevigor 

Could you please post output of  ```rpm -qa | grep -i calamari``` ```supervisord -v```

I want to make sure which version is causing this problem 

```
[root@ceph-node1 osd]# rpm -qa | grep -i calamari
calamari-server-1.3.0.1-49_g828960a.el7.centos.x86_64
calamari-clients-1.2.2-32_g931ee58.el7.centos.x86_64
[root@ceph-node1 osd]#
[root@ceph-node1 osd]# supervisord -v
3.0
[root@ceph-node1 osd]#
```

**Comment by moiseevigor** [comment]
As I said we use ubuntu 14.04 64bit, here is all fingerprints, sorry man I used some nonstandard installation procedure since I see 1.0 version which is not true

```
# dpkg -l | grep -i calamari
ii  calamari-server                     1.0.0-1                          amd64        Inktank package containing the Calamari management server
```
in any case the final deb file was compiled from https://github.com/ceph/calamari.git here is `git log`

```
commit 19d2423eea0f7ec9239063403af22e1ab80b2dba
Merge: b28c211 465e4cc
Author: Dan Mick <dan.mick@redhat.com>
Date:   Thu Jun 11 18:09:45 2015 -0700

    Merge pull request #298 from ceph/master_1.3_merge
    Master 1.3 merge
    Reviewed-by: Dan Mick <dmick@redhat.com>
```

the calamari-clients from https://github.com/ceph/calamari-clients.git and log is

```
commit 931ee5883cf52bb6a176634aabf8c41a628e84b8
Merge: b1fe77c b7a7f54
Author: Gregory Meno <gmeno@redhat.com>
Date:   Mon Apr 20 15:21:21 2015 -0400

    Merge pull request #91 from ceph/new-name
    
    change README to point at our new repo
```
In any case this is my notes on how I compile and install it

```
$ cd calamari
$ git pull
$ dpkg-buildpackage
$ sudo rm -rf /opt/calamari 
$ dpkg -i ../calamari-server_<version>_amd64.deb
```
