### ISSUE TITLE
Test failed happened at user admin is not exists

### ISSUE THREAD

**Issue by tantinevincent** [ceph/calamari#300]
Hi, I followed the Document (http://ceph.com/calamari/docs/development/dev_env.html#by-hand) to set up a development environment.  When executing "nosetests tests/test_permissions.py", a error is occured and the message as follow:

```
(foo)vagrant@calamari-1:~/calamari$ nosetests tests/test_permissions.py
[ERROR] User admin does not exist
E
======================================================================
ERROR: Check that we restrict readonly role from delete, put, patch, post
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/calamari/tests/test_permissions.py", line 16, in setUp
    self.change_role('admin', 'superuser')
  File "/home/vagrant/calamari/tests/test_permissions.py", line 28, in change_role
    assign_role(args)
  File "/home/vagrant/calamari/cthulhu/cthulhu/calamari_ctl.py", line 102, in assign_role
    raise CalamariUserError(str(e))
CalamariUserError: User matching query does not exist. Lookup parameters were {'username': 'admin'}
-------------------- >> begin captured logging << --------------------
calamari_ctl: ERROR: User admin does not exist
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.213s

FAILED (errors=1)
```

After reading the test file, I think the reason is the test use a fixed username 'admin'  and this username is not exists on my development environment.

```python
self.change_role('admin', 'superuser')
```

Maybe I should send a pull request to fix this?

**Comment by dmick** [comment]
Yep, the tests assume admin/admin.  I suppose we could add the ability to set that in test.conf; if you wanted to write such a pull request that'd be great
