### ISSUE TITLE
Server Error (500) after Calamari installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by gozek** [ceph/calamari#474]
Hey i just installed calamari on a Ubuntu 14,04 node, to manage via UI my 3 node cluster : 1 mon , 2 osds
I have followed the steps mentioned here ( until calamari-ctl initialize), without any errors during installation. Though, when i open my browser at localhost i am not redirected to the login page. When i move manually to the login page and sign in, the /dashboard page never loads and the browser informs me about Server Error (500).
I have checked the /var/log/calamari/calamari.log and i get : 
`2016-07-07 09:25:20,750 - ERROR - django.request Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/opt/calamari/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/calamari/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/calamari/venv/lib/python2.7/site-packages/calamari_web-0.1-py2.7.egg/calamari_web/views.py", line 38, in dashboard
    clusters = client.list_clusters()
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/core.py", line 260, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/core.py", line 245, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/core.py", line 217, in _process_response
    reply_event = bufchan.recv(timeout)
  File "/opt/calamari/venv/lib/python2.7/site-packages/zerorpc/channel.py", line 267, in recv
    event = self._input_queue.get(timeout=timeout)
  File "/opt/calamari/venv/lib/python2.7/site-packages/gevent/queue.py", line 200, in get
    result = waiter.get()
  File "/opt/calamari/venv/lib/python2.7/site-packages/gevent/hub.py", line 575, in get
    return self.hub.switch()
  File "/opt/calamari/venv/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
LostRemote: Lost remote after 10s heartbeat
` 

Also this is the content of /var/log/httpd_error.log : 
`[Thu Jul 07 09:19:45.517929 2016] [:warn] [pid 3099:tid 140165044348672] mod_wsgi (pid=3099): Callback registration for signal 2 ignored.
[Thu Jul 07 09:19:45.521142 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 255, in __call__
[Thu Jul 07 09:19:45.521163 2016] [:warn] [pid 3099:tid 140165044348672]     response = self.get_response(request)
[Thu Jul 07 09:19:45.521168 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
[Thu Jul 07 09:19:45.521190 2016] [:warn] [pid 3099:tid 140165044348672]     resolver_match = resolver.resolve(request.path_info)
[Thu Jul 07 09:19:45.521195 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 319, in resolve
[Thu Jul 07 09:19:45.521199 2016] [:warn] [pid 3099:tid 140165044348672]     for pattern in self.url_patterns:
[Thu Jul 07 09:19:45.521202 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 347, in url_patterns
[Thu Jul 07 09:19:45.521206 2016] [:warn] [pid 3099:tid 140165044348672]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Thu Jul 07 09:19:45.521209 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
[Thu Jul 07 09:19:45.521212 2016] [:warn] [pid 3099:tid 140165044348672]     self._urlconf_module = import_module(self.urlconf_name)
[Thu Jul 07 09:19:45.521216 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Thu Jul 07 09:19:45.521220 2016] [:warn] [pid 3099:tid 140165044348672]     __import__(name)
[Thu Jul 07 09:19:45.521223 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/calamari_web-0.1-py2.7.egg/calamari_web/urls.py", line 20, in <module>
[Thu Jul 07 09:19:45.521226 2016] [:warn] [pid 3099:tid 140165044348672]     url(r'^api/v1/', include('calamari_rest.urls.v1')),
[Thu Jul 07 09:19:45.521230 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 25, in include
[Thu Jul 07 09:19:45.521233 2016] [:warn] [pid 3099:tid 140165044348672]     urlconf_module = import_module(urlconf_module)
[Thu Jul 07 09:19:45.521237 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
[Thu Jul 07 09:19:45.521240 2016] [:warn] [pid 3099:tid 140165044348672]     __import__(name)
[Thu Jul 07 09:19:45.521244 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/calamari_rest_api-0.1-py2.7.egg/calamari_rest/urls/v1.py", line 3, in <module>
[Thu Jul 07 09:19:45.521247 2016] [:warn] [pid 3099:tid 140165044348672]     import calamari_rest.views.v1
[Thu Jul 07 09:19:45.521251 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/calamari_rest_api-0.1-py2.7.egg/calamari_rest/views/v1.py", line 38, in <module>
[Thu Jul 07 09:19:45.521255 2016] [:warn] [pid 3099:tid 140165044348672]     from calamari_rest.views.server_metadata import get_local_grains
[Thu Jul 07 09:19:45.521261 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/calamari_rest_api-0.1-py2.7.egg/calamari_rest/views/server_metadata.py", line 11, in <module>
[Thu Jul 07 09:19:45.521265 2016] [:warn] [pid 3099:tid 140165044348672]     from calamari_common.salt_wrapper import master_config, _create_loader, client_config, MasterPillarUtil
[Thu Jul 07 09:19:45.521270 2016] [:warn] [pid 3099:tid 140165044348672]   File "/opt/calamari/venv/lib/python2.7/site-packages/calamari_common-0.1-py2.7.egg/calamari_common/salt_wrapper.py", line 43, in <module>
[Thu Jul 07 09:19:45.521273 2016] [:warn] [pid 3099:tid 140165044348672]     from salt.key import Key  # noqa
[Thu Jul 07 09:19:45.521277 2016] [:warn] [pid 3099:tid 140165044348672]   File "/usr/lib/python2.7/dist-packages/salt/key.py", line 24, in <module>
[Thu Jul 07 09:19:45.521280 2016] [:warn] [pid 3099:tid 140165044348672]     import salt.daemons.masterapi
[Thu Jul 07 09:19:45.521284 2016] [:warn] [pid 3099:tid 140165044348672]   File "/usr/lib/python2.7/dist-packages/salt/daemons/masterapi.py", line 37, in <module>
[Thu Jul 07 09:19:45.521290 2016] [:warn] [pid 3099:tid 140165044348672]     from salt.pillar import git_pillar
[Thu Jul 07 09:19:45.521294 2016] [:warn] [pid 3099:tid 140165044348672]   File "/usr/lib/python2.7/dist-packages/salt/pillar/git_pillar.py", line 208, in <module>
[Thu Jul 07 09:19:45.521297 2016] [:warn] [pid 3099:tid 140165044348672]     import salt.utils.gitfs
[Thu Jul 07 09:19:45.521301 2016] [:warn] [pid 3099:tid 140165044348672]   File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 70, in <module>
[Thu Jul 07 09:19:45.521304 2016] [:warn] [pid 3099:tid 140165044348672]     import git
[Thu Jul 07 09:19:45.521308 2016] [:warn] [pid 3099:tid 140165044348672]   File "/usr/lib/python2.7/dist-packages/git/__init__.py", line 28, in <module>
[Thu Jul 07 09:19:45.521311 2016] [:warn] [pid 3099:tid 140165044348672]     _init_externals()
[Thu Jul 07 09:19:45.521314 2016] [:warn] [pid 3099:tid 140165044348672]   File "/usr/lib/python2.7/dist-packages/git/__init__.py", line 20, in _init_externals
[Thu Jul 07 09:19:45.521318 2016] [:warn] [pid 3099:tid 140165044348672]     import gitdb
[Thu Jul 07 09:19:45.521321 2016] [:warn] [pid 3099:tid 140165044348672]   File "/usr/lib/python2.7/dist-packages/gitdb/__init__.py", line 25, in <module>
[Thu Jul 07 09:19:45.521324 2016] [:warn] [pid 3099:tid 140165044348672]     _init_externals()
[Thu Jul 07 09:19:45.521328 2016] [:warn] [pid 3099:tid 140165044348672]   File "/usr/lib/python2.7/dist-packages/gitdb/__init__.py", line 17, in _init_externals
[Thu Jul 07 09:19:45.521331 2016] [:warn] [pid 3099:tid 140165044348672]     __import__(module)
[Thu Jul 07 09:19:45.521334 2016] [:warn] [pid 3099:tid 140165044348672]   File "/usr/lib/python2.7/dist-packages/async/__init__.py", line 36, in <module>
[Thu Jul 07 09:19:45.521337 2016] [:warn] [pid 3099:tid 140165044348672]     _init_signals()
[Thu Jul 07 09:19:45.521341 2016] [:warn] [pid 3099:tid 140165044348672]   File "/usr/lib/python2.7/dist-packages/async/__init__.py", line 26, in _init_signals
`
Any ideas about what is failing ? Thanks a lot

**Comment by GregMeno** [comment]
@gozek This looks like a failure to communicate with the cthulhu service. Is it running?
supervisorctl status cthulhu
are there errors contained in /var/log/calamari/cthulhu.log ?
