### ISSUE TITLE
Calamari not working Ubuntu 16.04

### ISSUE THREAD

**Issue by boxdaxter** [ceph/calamari#503]
Hi, 

I Installed a functional CEPH cluster under ubuntu 16.04. Now I'm trying to install calamari, but after severals attemps I'm not successful.

After fix all the dependencies and installa calamari-server on my ceph-admin, I get the next error when I try to run #root@ceph-admin:~# calamari-ctl initialize

`Traceback (most recent call last):
  File "/usr/bin/calamari-ctl", line 9, in <module>
    load_entry_point('calamari-cthulhu==0.1', 'console_scripts', 'calamari-ctl')()
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/calamari_ctl.py", line 8, in <module>
    from alembic import command
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/alembic/__init__.py", line 8, in <module>
    from . import op
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/alembic/op.py", line 1, in <module>
    from .operations import Operations
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/alembic/operations.py", line 3, in <module>
    from sqlalchemy.types import NULLTYPE, Integer
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/sqlalchemy/__init__.py", line 50, in <module>
    from .types import (
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/sqlalchemy/types.py", line 23, in <module>
    import datetime as dt
ImportError: No module named datetime
`
Could someone give me some idea? It's a bad idea use ubuntu 16.04 for calamari? I Should use redhat or older 14.04LTS ubuntu?

**Comment by Midori-ch** [comment]
Try
$ cd /opt/calamari ; source venv/bin/activate
$ sudo cp /usr/bin/python2.7 $(which python2.7)
$ calamari-ctl initialize

**Comment by dunedinit** [comment]
That fixed the issue for us thanks

We configured Calamari on 16.04

1. https://repo.saltstack.com/#ubuntu - Salt
2. https://www.openattic.org/posts/get-calamari-running-on-ubuntu-1404/ - Calamari
3. This post

**Comment by benlu36** [comment]
Other Error:  "Configuration not found at /etc/calamari/calamari.conf"

OS:  Ubuntu 16.04.4 LTS
cephuser@ceph-mon-03:~$ ceph --version
ceph version 12.2.4 (52085d5249a80c5f5121a76d6288429f35e4e77b) luminous (stable)
cephuser@ceph-mon-03:~$ ceph -s
  cluster:
    id:     5f185d1a-3208-4bed-991e-c69de349c679
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum ceph-mon-01,ceph-mon-02,ceph-mon-03
    mgr: ceph-admin-01(active)
    osd: 9 osds: 9 up, 9 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 bytes
    usage:   9519 MB used, 82604 MB / 92124 MB avail
    pgs:

Installed calamari and salt:

cephuser@ceph-mon-03:~$ sudo dpkg -l | egrep 'calamari|salt'
iU  calamari-clients                     1.3.1.1-1trusty                            all          Inktank Calamari user interface
iU  calamari-server                      1.3.1.1-1trusty                            amd64        Inktank package containing the Calamari management server
ri  salt-common                          2018.3.0+ds-1                              all          shared libraries that salt requires for all packages
ri  salt-master                          2018.3.0+ds-1                              all          remote manager to administer servers via salt
ri  salt-minion                          2018.3.0+ds-1                              all          client package for salt, the distributed remote execution system

Error:

cephuser@ceph-mon-03:~$ sudo calamari-ctl initialize
Traceback (most recent call last):
  File "/usr/bin/calamari-ctl", line 9, in <module>
    load_entry_point('calamari-cthulhu==0.1', 'console_scripts', 'calamari-ctl')()
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/calamari_ctl.py", line 8, in <module>
    from alembic import command
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/alembic/__init__.py", line 8, in <module>
    from . import op
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/alembic/op.py", line 1, in <module>
    from .operations import Operations
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/alembic/operations.py", line 3, in <module>
    from sqlalchemy.types import NULLTYPE, Integer
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/sqlalchemy/__init__.py", line 50, in <module>
    from .types import (
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/sqlalchemy/types.py", line 23, in <module>
    import datetime as dt
ImportError: No module named datetime

------------------------------------------------------------------------------------------------------------
cephuser@ceph-mon-03:~$ cd /opt/calamari ; source venv/bin/activate
(venv)cephuser@ceph-mon-03:/opt/calamari$ sudo cp /usr/bin/python2.7 $(which python2.7)
-------------------------------------------------------------------------------------------------------------
(venv)cephuser@ceph-mon-03:/opt/calamari$ sudo calamari-ctl initialize
Traceback (most recent call last):
  File "/usr/bin/calamari-ctl", line 9, in <module>
    load_entry_point('calamari-cthulhu==0.1', 'console_scripts', 'calamari-ctl')()
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/calamari_ctl.py", line 26, in <module>
    from cthulhu.log import FORMAT
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/log.py", line 4, in <module>
    config = CalamariConfig()
  File "/opt/calamari/venv/local/lib/python2.7/site-packages/calamari_common-0.1-py2.7.egg/calamari_common/config.py", line 30, in __init__
    raise ConfigNotFound("Configuration not found at %s" % self.path)
calamari_common.config.ConfigNotFound: Configuration not found at /etc/calamari/calamari.conf

Any one knows how to fix this error?
