### ISSUE TITLE
gevent.hub.LoopExit: This operation would block forever

### ISSUE THREAD

**Issue by F3ngdw** [ceph/calamari#533]
After running the program normally for a period of time, an error suddenly occurs：
```
Traceback (most recent call last):
  File "/opt/calamari/venv/bin/cthulhu-manager", line 9, in <module>
    load_entry_point('calamari-cthulhu==0.1', 'console_scripts', 'cthulhu-manager')()
  File "/opt/calamari/venv/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/manager/manager.py", line 1156, in main
    complete.wait(timeout=1)
  File "/opt/calamari/venv/lib/python2.7/site-packages/gevent/event.py", line 77, in wait
    result = self.hub.switch()
  File "/opt/calamari/venv/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: This operation would block forever
```
Has anyone encountered the same problem before? How to solve it?
```[tasklist]
### Tasks
```

**Comment by sebastian-philipp** [comment]
> How to solve it?

I'd probably move away from Calamari.
